<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a</name>
   <tag></tag>
   <elementGuidId>80d82c82-37ff-449a-98cb-c4614e7dc9b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='opt']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#opt > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://adclick.g.doubleclick.net/pcs/click%253Fxai%253DAKAOjss_8PYJdnsg-uqD_snjswLcHjbQtm7LfuFnajOzLaTZf1WJAro0Ggft2gK7O0txPhzP9rL9My7aDagZ77NsraVbX-LrtWJS6oOPZ0DqQDCvfk6r5lTBBPdEf1o_RUh6Z2XeRGJ7irASX0NdBiCzRHLyL9eHDLKNUTOLNHS7dbtxbgR39n6UkkIs9mVXQfTm6sq4S8kWZkthjnoSzlnMZzGXH6sQhSaSVijlJpSamHAne-JFfYYGfvZ6WZETcqgxUz7AOmrawLzwhUKyhpKVbY-gXd6ReVmIYLrQDEymqQ%2526sai%253DAMfl-YTucUDpD1GcReWlSQ_Hsb7f1bflUUbsyYLiPkk56-tmzviBoVqZe4TNPecZrO1h4vVwiUJUNe5xAdOYqzlZqI0suIk0mkufWY9oxVO3ar_OoDkZLfADwXgeLRFjeAs%2526sig%253DCg0ArKJSzAXiy7eSj0lOEAE%2526urlfix%253D1%2526adurl%253Dhttps://www.chevroletarabia.com/eg-ar/request-a-quote%3Futm_source%3DContact%2520Cars%26utm_medium%3DCPM%26utm_campaign%3DCaptiva%25202021</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;opt&quot;)/a[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='opt']/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://adclick.g.doubleclick.net/pcs/click%253Fxai%253DAKAOjss_8PYJdnsg-uqD_snjswLcHjbQtm7LfuFnajOzLaTZf1WJAro0Ggft2gK7O0txPhzP9rL9My7aDagZ77NsraVbX-LrtWJS6oOPZ0DqQDCvfk6r5lTBBPdEf1o_RUh6Z2XeRGJ7irASX0NdBiCzRHLyL9eHDLKNUTOLNHS7dbtxbgR39n6UkkIs9mVXQfTm6sq4S8kWZkthjnoSzlnMZzGXH6sQhSaSVijlJpSamHAne-JFfYYGfvZ6WZETcqgxUz7AOmrawLzwhUKyhpKVbY-gXd6ReVmIYLrQDEymqQ%2526sai%253DAMfl-YTucUDpD1GcReWlSQ_Hsb7f1bflUUbsyYLiPkk56-tmzviBoVqZe4TNPecZrO1h4vVwiUJUNe5xAdOYqzlZqI0suIk0mkufWY9oxVO3ar_OoDkZLfADwXgeLRFjeAs%2526sig%253DCg0ArKJSzAXiy7eSj0lOEAE%2526urlfix%253D1%2526adurl%253Dhttps://www.chevroletarabia.com/eg-ar/request-a-quote%3Futm_source%3DContact%2520Cars%26utm_medium%3DCPM%26utm_campaign%3DCaptiva%25202021')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/a</value>
   </webElementXpaths>
</WebElementEntity>
