<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>canvas__uid_1epct2b6586j1g611qn77mn1m52c_canvas</name>
   <tag></tag>
   <elementGuidId>3a8af86d-1321-481d-a95f-f7c429f845c4</elementGuidId>
   <imagePath>Screenshots/Targets/Page_   - ContactCars.com/canvas__uid_1epct2b6586j1g611qn77mn1m52c_canvas.png</imagePath>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#uid_1epct2b6586j1g611qn77mn1m52c_canvas</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//canvas[@id='uid_1epct2b6586j1g611qn77mn1m52c_canvas']</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value>Screenshots/Targets/Page_   - ContactCars.com/canvas__uid_1epct2b6586j1g611qn77mn1m52c_canvas.png</value>
      </entry>
   </selectorCollection>
   <selectorMethod>IMAGE</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>canvas</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>172</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>120</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uid_1epct2b6586j1g611qn77mn1m52c_canvas</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uid_1epct2b6586j1g611qn77mn1m52c_canvas&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//canvas[@id='uid_1epct2b6586j1g611qn77mn1m52c_canvas']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='o_1epct2asnjpu1lad1kth4q518t7a']/span/canvas</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//canvas</value>
   </webElementXpaths>
</WebElementEntity>
