<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>carimg1</name>
   <tag></tag>
   <elementGuidId>e4a330c8-77b9-405d-b33b-c280ad197712</elementGuidId>
   <imagePath>Screenshots/Targets/Page_   - ContactCars.com/canvas__uid_1epfk8p2ehrilmd11pk1fk7a6cc_canvas.png</imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//canvas[@id='uid_1epfk8p2ehrilmd11pk1fk7a6cc_canvas']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#uid_1epfk8p2ehrilmd11pk1fk7a6cc_canvas</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value>Screenshots/Targets/Page_   - ContactCars.com/canvas__uid_1epfk8p2ehrilmd11pk1fk7a6cc_canvas.png</value>
      </entry>
   </selectorCollection>
   <selectorMethod>IMAGE</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>canvas</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>172</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>120</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uid_1epfk8p2ehrilmd11pk1fk7a6cc_canvas</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uid_1epfk8p2ehrilmd11pk1fk7a6cc_canvas&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//canvas[@id='uid_1epfk8p2ehrilmd11pk1fk7a6cc_canvas']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='o_1epfk8p1i2v24vjc0p1giu5dma']/span/canvas</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//canvas</value>
   </webElementXpaths>
</WebElementEntity>
